### PR TITLE
[v0.5.0] update docker-compose file version to 3.8

### PR DESCRIPTION
**Pull request by LeonardoMariano**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
The docker-compose file version has been updated to 3.8

* **What is the current behavior?** (You can also link to an open issue here)
The docker-compose file version is 2.1

* **What is the new behavior (if this is a feature change)?**
The docker-compose file version is 3.8

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
Yes, this PR is connected to dojot/dojot#1722

* **Other information**:

### CODE REVIEW

**Review by andersonluisribeiro — DISMISSED** [review]
👍

**Review by eduardogmisiuk — APPROVED** [review]

**Comment by mprevide** [comment]
I think It needs to change de required docker-compose and docker in readme... 
And create a PR to dev too.

**Review by mprevide — DISMISSED** [review]
I think it is necessary to change the version required for docker-compose and docker in the readme...
And create a PR to dev too.

**Review by eduardogmisiuk — APPROVED** [review]

**Comment by eduardogmisiuk** [comment]
Prepend to the PR title the version, like `[v0.5.0]`. Do it to the `[dev]` PR too.

**Review by andersonluisribeiro — APPROVED** [review]
:+1:

**Pull request merged**
