### PR TITLE
fix: fixing flowbroker conflicting network names

### PR DESCRIPTION
**Pull request by andrewjschuang**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix.

* **What is the current behavior?** (You can also link to an open issue here)
Flowbroker couldn't find the correct network if there were two or more networks containing 'flowbroker' in their names.

* **What is the new behavior (if this is a feature change)?**
The network name has to be defined by the user and, being each one unique, there won't be any problems in finding the correct one.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
 This is connected to dojot/dojot#665.

* **Other information**:

### CODE REVIEW

**Comment by giovannicuriel** [comment]
Just for the record: this will need Docker engine > 17.12 and docker-compose > 1.18

**Comment by raulnegreiros** [comment]
> Just for the record: 'name' for networks appeared in [docker-compose file version 3.5](https://docs.docker.com/compose/compose-file/compose-versioning/#version-35), which is supported by [docker engine > 17.12](https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix) and [docker-compose > 1.18](https://docs.docker.com/release-notes/docker-compose/#1180-2017-12-18)

Maybe we should update the version tag on `.yml` file to 3.5. What do you think?

**Comment by giovannicuriel** [comment]
I agree @raulnegreiros

**Comment by raulnegreiros** [comment]
> I agree @raulnegreiros.
> But there are a few changes to be made - the syntax for version 3.5 is somewhat different than for 2.1.
> I'd wait a little bit - after releasing the new version this could be changed.

Agree.

**Pull request merged**
