### PR TITLE
feat: added payload max size env variables

### PR DESCRIPTION
**Pull request by jonaphael**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:
dojot/dojot#1288

### CODE REVIEW

**Comment by mprevide** [comment]
Does it really need to be here?

**Comment by muhamedcpqd** [comment]
@mprevide , now that you have appointed that, its a good point to add a doc. But adding too the env variable maybe will helps the final user to identify the use of that variable..

**Comment by mprevide** [comment]
Please, @jonaphael, it needs just to be added in the documentation.

**Comment by andersonluisribeiro** [comment]
Ticket review meeting: It doesn't make sense for dojot. The refactor will not be used.

**Pull request closed without merging**
